/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace Discount {
  export type StructStruct = {
    tokenContract: string;
    tokenIds: BigNumberish[];
    dateStart: BigNumberish;
    dateStop: BigNumberish;
    amountToUsePerUsableDiscount: BigNumberish;
    discount: BigNumberish;
    tokenType: BigNumberish;
    usable: boolean;
  };

  export type StructStructOutput = [
    string,
    BigNumber[],
    BigNumber,
    BigNumber,
    BigNumber,
    number,
    number,
    boolean
  ] & {
    tokenContract: string;
    tokenIds: BigNumber[];
    dateStart: BigNumber;
    dateStop: BigNumber;
    amountToUsePerUsableDiscount: BigNumber;
    discount: number;
    tokenType: number;
    usable: boolean;
  };
}

export interface ICreateDiscountInterface extends utils.Interface {
  contractName: "ICreateDiscount";
  functions: {
    "createDiscount((address,uint256[],uint256,uint256,uint256,uint32,uint8,bool))": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createDiscount",
    values: [Discount.StructStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "createDiscount",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ICreateDiscount extends BaseContract {
  contractName: "ICreateDiscount";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ICreateDiscountInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createDiscount(
      discount: Discount.StructStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  createDiscount(
    discount: Discount.StructStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createDiscount(
      discount: Discount.StructStruct,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    createDiscount(
      discount: Discount.StructStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createDiscount(
      discount: Discount.StructStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
