name: Merge Guard
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: 
      - ready_for_review
      - review_requested
jobs:
  Compilation-status:
    name: Compilation status
    runs-on: ubuntu-latest
    steps:
      - name: Checkout set-up
        uses: actions/checkout@v3
      - name: Node set-up
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - name: Location set-up
        run: npm install
      - name: Compilation status
        run: npm run compile
        env: 
          ETH_ACCOUNT_PRIVATE_KEY: ${{ secrets.ETH_ACCOUNT_PRIVATE_KEY }}
          ETH_ACCOUNT_PUBLIC_KEY: ${{ secrets.ETH_ACCOUNT_PUBLIC_KEY }}
          POLYSCAN_API_KEY: ${{ secrets.POLYSCAN_API_KEY }}
          MUMBAI_URL: ${{ secrets.MUMBAI_URL }}
          RINKEBY_URL: ${{ secrets.RINKEBY_URL }}
  Deployment-functionalities:
    name: Deployment functionalities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout set-up
        uses: actions/checkout@v3
      - name: Node set-up
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - name: Location set-up
        run: npm install
      - name: Deployment functionalities
        run: npm run compile && npm run deployment-workflow-test
        env: 
          ETH_ACCOUNT_PRIVATE_KEY: ${{ secrets.ETH_ACCOUNT_PRIVATE_KEY }}
          ETH_ACCOUNT_PUBLIC_KEY: ${{ secrets.ETH_ACCOUNT_PUBLIC_KEY }}
          POLYSCAN_API_KEY: ${{ secrets.POLYSCAN_API_KEY }}
          MUMBAI_URL: ${{ secrets.MUMBAI_URL }}
          RINKEBY_URL: ${{ secrets.RINKEBY_URL }}
  Core-functionalities:
    name: Core functionalities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout set-up
        uses: actions/checkout@v3
      - name: Node set-up
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - name: Location set-up
        run: npm install
      - name: Core functionalities
        run: npm run compile && npm run core-workflow-test
        env: 
          ETH_ACCOUNT_PRIVATE_KEY: ${{ secrets.ETH_ACCOUNT_PRIVATE_KEY }}
          ETH_ACCOUNT_PUBLIC_KEY: ${{ secrets.ETH_ACCOUNT_PUBLIC_KEY }}
          POLYSCAN_API_KEY: ${{ secrets.POLYSCAN_API_KEY }}
          MUMBAI_URL: ${{ secrets.MUMBAI_URL }}
          RINKEBY_URL: ${{ secrets.RINKEBY_URL }}
  Race-statistics-generation:
    name: Race statistics generation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout set-up
        uses: actions/checkout@v3
      - name: Node set-up
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - name: Location set-up
        run: npm install
      - name: Race statistics generation
        run: npm run compile && npm run races-statistics-generation-test
        env: 
          ETH_ACCOUNT_PRIVATE_KEY: ${{ secrets.ETH_ACCOUNT_PRIVATE_KEY }}
          ETH_ACCOUNT_PUBLIC_KEY: ${{ secrets.ETH_ACCOUNT_PUBLIC_KEY }}
          POLYSCAN_API_KEY: ${{ secrets.POLYSCAN_API_KEY }}
          MUMBAI_URL: ${{ secrets.MUMBAI_URL }}
          RINKEBY_URL: ${{ secrets.RINKEBY_URL }}
  Full-deployment-functionalities:
    name: Full deployment functionalities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout set-up
        uses: actions/checkout@v3
      - name: Node set-up
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - name: Location set-up
        run: npm install
      - name: Full deployment functionalities
        run: npm run compile && npm run full-deployment-workflow-test
        env: 
          ETH_ACCOUNT_PRIVATE_KEY: ${{ secrets.ETH_ACCOUNT_PRIVATE_KEY }}
          ETH_ACCOUNT_PUBLIC_KEY: ${{ secrets.ETH_ACCOUNT_PUBLIC_KEY }}
          POLYSCAN_API_KEY: ${{ secrets.POLYSCAN_API_KEY }}
          MUMBAI_URL: ${{ secrets.MUMBAI_URL }}
          RINKEBY_URL: ${{ secrets.RINKEBY_URL }}