name: Race Statistics Generation
on: push
jobs:
  Race-statistics-generation:
    name: Race statistics generation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout set-up
        uses: actions/checkout@v3
      - name: Node set-up
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - name: Location set-up
        run: npm install
      - name: Race statistics generation
        run: npm run compile && npm run races-statistics-generation-test
        env: 
          ETH_ACCOUNT_PRIVATE_KEY: ${{ secrets.ETH_ACCOUNT_PRIVATE_KEY }}
          ETH_ACCOUNT_PUBLIC_KEY: ${{ secrets.ETH_ACCOUNT_PUBLIC_KEY }}
          POLYSCAN_API_KEY: ${{ secrets.POLYSCAN_API_KEY }}
          MUMBAI_URL: ${{ secrets.MUMBAI_URL }}
          RINKEBY_URL: ${{ secrets.RINKEBY_URL }}