name: Contracts functionality testing
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout set-up
        uses: actions/checkout@v3
      - name: Node set-up
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - name: Location set-up
        run: npm install
      - name: Location set-up verifications
        run: node --version && npm --version && npx --version && echo "Deployer address ${{ secrets.ETH_ACCOUNT_PUBLIC_KEY }}"
      - name: Unit tests
        run: npx hardhat test
        env: 
          ETH_ACCOUNT_PRIVATE_KEY: ${{ secrets.ETH_ACCOUNT_PRIVATE_KEY }}
          ETH_ACCOUNT_PRIVATE_KEY2: ${{ secrets.ETH_ACCOUNT_PRIVATE_KEY2 }}
          ETH_ACCOUNT_PUBLIC_KEY: ${{ secrets.ETH_ACCOUNT_PUBLIC_KEY }}
          ETH_ACCOUNT_PUBLIC_KEY2: ${{ secrets.ETH_ACCOUNT_PUBLIC_KEY2 }}
          RINKEBY_ETHERSCAN_API_KEY: ${{ secrets.RINKEBY_ETHERSCAN_API_KEY }}
          RINKEBY_URL: ${{ secrets.RINKEBY_URL }}
